# wandb sweep config
program: train.py
method: bayes
metric:
  name: val_BinaryJaccardIndex
  goal: maximize

name: param_tuning_deeplabv3plus
project: oks

parameters:

  experiments:
    value: "semantic-segmentation/LC_130723_oks.yaml"

  # augmentations_train:
  #   values: [none, 'position/random_horizontal_flip.yaml']

  batch_size:
    values: [ 2, 4, 8 ]

  models.encoder_name:
    values: ['resnet34', 'resnet50', 'resnet101']

  optimizers:
    values: ['lion.yaml', 'adam.yaml']

#  schedulers:
#    values: ['auto.yaml', 'cosine_annealing.yaml', 'custom.yaml']

  optimizers.lr:
    min: 0.0035
    max: 0.0070

  epochs:
    values: [15, 20]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
